# Generated by Django 5.1.6 on 2025-03-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/image', verbose_name='превью (изображение)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('publication_sign', models.BooleanField(verbose_name='признак публикации')),
                ('views_counter', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['title', 'created_at', 'views_counter'],
            },
        ),
    ]
