# Generated by Django 5.1.6 on 2025-03-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование продукта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание продукта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='изображение продукта')),
                ('price', models.IntegerField(verbose_name='цена за покупку')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания карточки продукта')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='дата последнего изменения карточки продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'category', 'price'],
            },
        ),
    ]
